name: Machine Learning Workflow

on:
  push:
    branches: [ main ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mlflow==2.7.1 dagshub pandas scikit-learn joblib
          pip install "requests<2.29.0" "urllib3<2.0.0"

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: AndiArif123
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject_Folder
          # Ganti experiment-name agar sesuai dengan dataset Cancer
          mlflow run . --env-manager=local --experiment-name Cancer_Modelling_Andi

      - name: Upload Model to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          # Ganti nama artifact agar tidak ada kata 'iris'
          name: cancer-model-artifact
          path: |
            MLProject_Folder/model.pkl
            MLProject_Folder/classification_report.json   

      - name: Build Docker Image (Manual Mode)
        run: |
          cd MLProject_Folder
          MODEL_FILE=$(find mlruns -name "model.pkl" | head -n 1)
          echo "Model file ditemukan di: $MODEL_FILE"
          cp "$MODEL_FILE" ./model.pkl
          
          cat <<EOF > Dockerfile
          FROM python:3.9-slim
          WORKDIR /app
          COPY model.pkl /app/model.pkl
          RUN pip install scikit-learn pandas joblib
          CMD ["python", "-c", "import joblib; model = joblib.load('model.pkl'); print('Model Cancer loaded successfully!')"]
          EOF
          
          # Ganti nama tag image Docker
          docker build -t andi-cancer-model .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        run: |
          # Ganti nama repository Docker Hub
          docker tag andi-cancer-model ${{ secrets.DOCKER_USERNAME }}/andi-cancer-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/andi-cancer-model:latest
