name: Machine Learning CI

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mlflow==2.7.1 dagshub pandas scikit-learn joblib matplotlib seaborn mlserver mlserver-mlflow

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: AndiArif123
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject_Folder
          mlflow run . --no-conda

      - name: Upload Artifacts to GitHub (backup)
        uses: actions/upload-artifact@v4
        with:
          name: ml-model-artifacts
          path: |
            MLProject_Folder/model.pkl
            MLProject_Folder/model_output/
            MLProject_Folder/classification_report.json

      - name: Build Docker Image
        run: |
          LATEST_RUN=$(mlflow runs list --experiment-name AndiArif --max-results 1 --output json | jq -r '.[0].info.run_id')
          mlflow models build-docker \
            -m "runs:/$LATEST_RUN/artifacts/model" \
            -n "andi-iris-model" \
            --enable-mlserver

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker tag andi-iris-model ${{ secrets.DOCKER_USERNAME }}/andi-iris-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/andi-iris-model:latest
