name: Machine Learning CI

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mlflow==2.7.1 dagshub pandas scikit-learn joblib mlserver mlserver-mlflow

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: AndiArif123
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          # Paksa menggunakan tracking DagsHub di level CLI
          MLFLOW_TRACKING_URI: https://dagshub.com/AndiArif123/Eksperimen_SML_Andi-Arif-Abdillah.mlflow
        run: |
          cd MLProject_Folder
          # Tambahkan retries jika gagal koneksi ke server
          mlflow run . --env-manager=local --experiment-name AndiArif

      - name: Upload Artifacts to GitHub (backup)
        uses: actions/upload-artifact@v4
        with:
          name: ml-model-artifacts
          path: |
            MLProject_Folder/model.pkl
            MLProject_Folder/model_output/
            MLProject_Folder/classification_report.json

      - name: Build Docker Image
        env:
          MLFLOW_TRACKING_USERNAME: AndiArif123
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/AndiArif123/Eksperimen_SML_Andi-Arif-Abdillah.mlflow
        run: |
          sleep 15
          EXP_ID=$(mlflow experiments get-by-name -n AndiArif | grep "Experiment ID" | awk '{print $3}')
          
          LATEST_RUN=$(mlflow runs list --experiment-id $EXP_ID --max-results 1 --output json | jq -r '.[0].info.run_id')
          
          echo "Building Docker for Run ID: $LATEST_RUN"
          
          # 3. Build docker dengan path model yang benar
          mlflow models build-docker \
            -m "runs:/$LATEST_RUN/model" \
            -n "andi-iris-model" \
            --enable-mlserver

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker tag andi-iris-model ${{ secrets.DOCKER_USERNAME }}/andi-iris-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/andi-iris-model:latest
