name: Machine Learning CI

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install mlflow==2.7.1 dagshub pandas scikit-learn joblib mlserver mlserver-mlflow
          pip install "requests<2.29.0" "urllib3<2.0.0"

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: AndiArif123
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject_Folder
          
          mlflow run . --env-manager=local --experiment-name AndiArif

      - name: Upload Artifacts to GitHub (backup)
        uses: actions/upload-artifact@v4
        with:
          name: ml-model-artifacts
          path: |
            MLProject_Folder/model.pkl
            MLProject_Folder/model_output/
            MLProject_Folder/classification_report.json

      - name: Build and Push Docker Image
        env:
          MLFLOW_TRACKING_USERNAME: AndiArif123
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/AndiArif123/Eksperimen_SML_Andi-Arif-Abdillah.mlflow
        run: |
          cd MLProject_Folder
          # 2. Cari model di folder lokal yang baru saja dibuat
          MODEL_PATH=$(find mlruns -name "model" -type d | grep "artifacts/model" | head -n 1)
          echo "Model ditemukan di: $MODEL_PATH"
          
          # 3. Build Docker menggunakan file lokal tersebut
          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n "andi-iris-model" \
            --install-mlflow

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        run: |
          
          docker tag andi-iris-model ${{ secrets.DOCKER_USERNAME }}/andi-iris-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/andi-iris-model:latest
